# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ae17974287b9b9cb06e7e92ca82e3fdb829f9233396c2f1239f9cec3ab46556359d41b6fd89ae33db7cb92b6cbac9171cd8b6c596ca8c50a46f7a267fa24d56

test:
  secret_key_base: 963354448d1a007b9e9623c586803596328e0657499ea8cdef64cea6c074031cc46735373f3f2aedbf73f49e5f8d1499227e219d3e6dffe2df53c693a9b7f128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
